/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState, useRef, useEffect } from 'react';
import { 
  FileText, 
  Upload, 
  Activity, 
  Clipboard, 
  Printer, 
  CheckCircle2, 
  AlertCircle, 
  Loader2, 
  Languages, 
  User,
  Share2,
  ArrowRight,
  Stethoscope,
  Pill,
  History,
  Info
} from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';
import { GoogleGenAI } from "@google/genai";

// --- Types ---

interface Medication {
  name: string;
  dosage: string;
  frequency: string;
  purpose: string;
}

interface JargonPair {
  jargon: string;
  simple: string;
}

interface AnalysisResult {
  diagnosis: string;
  medications: Medication[];
  side_effects: string[];
  followup: string[];
  family_summary: string;
  original_vs_simple: JargonPair[];
  error?: string;
}

type Language = 'EN' | 'HI';

// --- Constants ---

const TRANSLATIONS = {
  EN: {
    demo: "Try Demo Mode",
    heroTitle: "Understand your medical records in ",
    heroTitleHighlight: "plain English.",
    heroSub: "Upload your discharge summary or prescription. MedBuddy removes the jargon so you can focus on recovery.",
    patientAge: "Patient Age",
    language: "Language",
    uploadText: "Click to upload or drag & drop",
    uploadSub: "PDF, JPG, or PNG (Max 10MB)",
    analyzeBtn: "Analyze Document",
    scanning: "Scanning Document...",
    steps: [
      "Converting File...",
      "Analyzing Jargon...",
      "Safety Check...",
      "Finalizing Dashboard"
    ],
    startNew: "Start New Analysis",
    whatsapp: "WhatsApp Summary",
    print: "Print Guide",
    diagnosis: "Diagnosis",
    medSchedule: "Medication Schedule",
    medicine: "Medicine",
    dosage: "Dosage",
    frequency: "Frequency",
    why: "Why?",
    jargonBuster: "Jargon Buster",
    nextSteps: "Next Steps",
    watchFor: "Watch For",
    contactDoctor: "Contact your doctor if symptoms persist.",
    generatedBy: "Generated by MedBuddy AI",
    printDisclaimer: "This is a simplified guide, not a substitute for medical advice.",
    dashboard: "MedBuddy Dashboard",
    footerDisclaimer: "Disclaimer: MedBuddy uses AI to simplify documents. Always verify medication dosages with your healthcare provider. Do not make medical decisions based solely on this dashboard.",
    copySuccess: "Summary copied to clipboard! You can now paste it in WhatsApp.",
    uploadError: "Please upload a document first.",
    fileSizeError: "File is too large. Maximum size is 10MB.",
    fileTypeError: "Invalid file type. Please upload a PDF, JPG, or PNG.",
    apiQuotaError: "AI limit reached. Please try again later.",
    apiSafetyError: "The document contains sensitive content that cannot be analyzed.",
    apiInvalidError: "The uploaded file does not appear to be a valid medical record.",
    genericError: "Failed to analyze document. Please try again."
  },
  HI: {
    demo: "डेमो मोड आज़माएं",
    heroTitle: "अपनी मेडिकल रिपोर्ट को ",
    heroTitleHighlight: "सरल भाषा में समझें।",
    heroSub: "अपनी डिस्चार्ज समरी या प्रिस्क्रिप्शन अपलोड करें। मेडबडी कठिन शब्दों को हटा देता है ताकि आप रिकवरी पर ध्यान केंद्रित कर सकें।",
    patientAge: "मरीज की उम्र",
    language: "भाषा",
    uploadText: "अपलोड करने के लिए क्लिक करें या फ़ाइल यहाँ खींचें",
    uploadSub: "PDF, JPG, या PNG (अधिकतम 10MB)",
    analyzeBtn: "दस्तावेज़ का विश्लेषण करें",
    scanning: "दस्तावेज़ स्कैन हो रहा है...",
    steps: [
      "फ़ाइल परिवर्तित हो रही है...",
      "कठिन शब्दों का विश्लेषण...",
      "सुरक्षा जांच...",
      "डैशबोर्ड तैयार हो रहा है"
    ],
    startNew: "नया विश्लेषण शुरू करें",
    whatsapp: "व्हाट्सएप सारांश",
    print: "गाइड प्रिंट करें",
    diagnosis: "निदान (Diagnosis)",
    medSchedule: "दवा का समय",
    medicine: "दवा",
    dosage: "खुराक",
    frequency: "कितनी बार",
    why: "क्यों?",
    jargonBuster: "कठिन शब्दों का अर्थ",
    nextSteps: "अगले कदम",
    watchFor: "इन बातों का ध्यान रखें",
    contactDoctor: "यदि लक्षण बने रहते हैं तो अपने डॉक्टर से संपर्क करें।",
    generatedBy: "मेडबडी एआई द्वारा जनरेट किया गया",
    printDisclaimer: "यह एक सरल गाइड है, चिकित्सा सलाह का विकल्प नहीं।",
    dashboard: "मेडबडी डैशबोर्ड",
    footerDisclaimer: "अस्वीकरण: मेडबडी दस्तावेजों को सरल बनाने के लिए एआई का उपयोग करता है। हमेशा अपने स्वास्थ्य सेवा प्रदाता के साथ दवा की खुराक की पुष्टि करें। केवल इस डैशबोर्ड के आधार पर चिकित्सा निर्णय न लें।",
    copySuccess: "सारांश क्लिपबोर्ड पर कॉपी हो गया! अब आप इसे व्हाट्सएप में पेस्ट कर सकते हैं।",
    uploadError: "कृपया पहले एक दस्तावेज़ अपलोड करें।",
    fileSizeError: "फ़ाइल बहुत बड़ी है। अधिकतम आकार 10MB है।",
    fileTypeError: "अमान्य फ़ाइल प्रकार। कृपया PDF, JPG, या PNG अपलोड करें।",
    apiQuotaError: "एआई सीमा समाप्त हो गई है। कृपया बाद में पुनः प्रयास करें।",
    apiSafetyError: "दस्तावेज़ में संवेदनशील सामग्री है जिसका विश्लेषण नहीं किया जा सकता।",
    apiInvalidError: "अपलोड की गई फ़ाइल एक वैध मेडिकल रिकॉर्ड नहीं लगती है।",
    genericError: "दस्तावेज़ का विश्लेषण करने में विफल। कृपया पुन: प्रयास करें।"
  }
};

const SYSTEM_PROMPT = `You are MedBuddy, a specialized medical document parser. 
TASK: Extract data from the provided image/PDF. 
STRICT RULES:
1. Do NOT provide medical advice or suggest new treatments.
2. If information is missing, use 'Not specified'. 
3. Medication dosages must be 100% verbatim.
4. If the document is NOT a medical record, return {"error": "Invalid document type"}.
5. Output ONLY a JSON object with these keys: diagnosis, medications (array of objects), side_effects (array), followup (array), family_summary (string), original_vs_simple (array of {jargon, simple}).
6. Adapt the 'family_summary' and 'simple' explanations for a patient of age {AGE} and in language {LANGUAGE}.`;

const DEMO_DATA: AnalysisResult = {
  diagnosis: "Post-Appendectomy (Recovery Phase)",
  medications: [
    { name: "Amoxicillin", dosage: "500mg", frequency: "3 times a day", purpose: "Prevent infection" },
    { name: "Paracetamol", dosage: "650mg", frequency: "Every 6 hours as needed", purpose: "Pain relief" },
    { name: "Pantoprazole", dosage: "40mg", frequency: "Once daily before breakfast", purpose: "Stomach protection" }
  ],
  side_effects: ["Mild nausea", "Drowsiness", "Loose stools"],
  followup: ["Wound check in 7 days", "Stitch removal on April 2nd", "Avoid heavy lifting for 4 weeks"],
  family_summary: "The surgery was successful. The patient needs rest, regular medicine to prevent infection, and a light diet. No heavy exercise for a month.",
  original_vs_simple: [
    { jargon: "Appendectomy", simple: "Surgery to remove the appendix" },
    { jargon: "Analgesic", simple: "Painkiller" },
    { jargon: "Prophylactic", simple: "Preventive treatment" }
  ]
};

// --- Components ---

export default function App() {
  const [file, setFile] = useState<File | null>(null);
  const [age, setAge] = useState<string>('30');
  const [language, setLanguage] = useState<Language>('EN');
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [step, setStep] = useState(0);
  const [result, setResult] = useState<AnalysisResult | null>(null);
  const [error, setError] = useState<string | null>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const t = TRANSLATIONS[language];

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      const selectedFile = e.target.files[0];
      
      // Validation: File Type
      const allowedTypes = ['image/jpeg', 'image/png', 'application/pdf'];
      if (!allowedTypes.includes(selectedFile.type)) {
        setError(t.fileTypeError);
        setFile(null);
        return;
      }

      // Validation: File Size (10MB)
      if (selectedFile.size > 10 * 1024 * 1024) {
        setError(t.fileSizeError);
        setFile(null);
        return;
      }

      setFile(selectedFile);
      setError(null);
    }
  };

  const fileToBase64 = (file: File): Promise<string> => {
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.readAsDataURL(file);
      reader.onload = () => {
        const base64String = (reader.result as string).split(',')[1];
        resolve(base64String);
      };
      reader.onerror = error => reject(error);
    });
  };

  const analyzeDocument = async () => {
    if (!file) {
      setError(t.uploadError);
      return;
    }

    setIsAnalyzing(true);
    setStep(0);
    setError(null);
    setResult(null);

    // Simulate progressive disclosure
    const stepInterval = setInterval(() => {
      setStep(prev => (prev < t.steps.length - 1 ? prev + 1 : prev));
    }, 1500);

    try {
      const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY! });
      const base64Data = await fileToBase64(file);
      
      const prompt = SYSTEM_PROMPT
        .replace('{AGE}', age)
        .replace('{LANGUAGE}', language === 'EN' ? 'English' : 'Hindi');

      const response = await ai.models.generateContent({
        model: "gemini-1.5-flash-latest",
        contents: [
          {
            parts: [
              { text: prompt },
              {
                inlineData: {
                  mimeType: file.type,
                  data: base64Data
                }
              }
            ]
          }
        ],
        config: {
          responseMimeType: "application/json"
        }
      });

      const text = response.text;
      const parsed: AnalysisResult = JSON.parse(text || '{}');

      if (parsed.error) {
        throw new Error(parsed.error);
      }

      setResult(parsed);
    } catch (err: any) {
      console.error(err);
      
      let userMessage = t.genericError;
      const errorMessage = err.message?.toLowerCase() || "";

      if (errorMessage.includes("quota") || errorMessage.includes("429")) {
        userMessage = t.apiQuotaError;
      } else if (errorMessage.includes("safety") || errorMessage.includes("blocked")) {
        userMessage = t.apiSafetyError;
      } else if (errorMessage.includes("invalid document type")) {
        userMessage = t.apiInvalidError;
      } else if (errorMessage.includes("api key")) {
        userMessage = "Invalid API configuration. Please contact support.";
      }

      setError(userMessage);
    } finally {
      clearInterval(stepInterval);
      setIsAnalyzing(false);
    }
  };

  const runDemo = () => {
    setIsAnalyzing(true);
    setStep(0);
    setError(null);
    setResult(null);

    const stepInterval = setInterval(() => {
      setStep(prev => (prev < t.steps.length - 1 ? prev + 1 : prev));
    }, 800);

    setTimeout(() => {
      clearInterval(stepInterval);
      setResult(DEMO_DATA);
      setIsAnalyzing(false);
    }, 3500);
  };

  const copyToWhatsApp = () => {
    if (!result) return;
    const text = `*MedBuddy Summary*\n\n*Diagnosis:* ${result.diagnosis}\n\n*Medications:*\n${result.medications.map(m => `- ${m.name} (${m.dosage}): ${m.frequency}`).join('\n')}\n\n*Summary:* ${result.family_summary}`;
    navigator.clipboard.writeText(text);
    alert(t.copySuccess);
  };

  return (
    <div className="min-h-screen flex flex-col">
      {/* Header */}
      <header className="bg-white border-b border-slate-200 sticky top-0 z-10 no-print">
        <div className="max-w-7xl mx-auto px-4 h-16 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="bg-brand p-2 rounded-lg animate-pulse-slow">
              <Stethoscope className="text-white w-6 h-6" />
            </div>
            <h1 className="text-2xl font-bold text-brand tracking-tight">MedBuddy</h1>
          </div>
          <div className="flex items-center gap-4">
            <button 
              onClick={runDemo}
              className="text-sm font-medium text-slate-600 hover:text-brand transition-colors"
            >
              {t.demo}
            </button>
            <div className="h-6 w-px bg-slate-200" />
            <div className="flex items-center gap-2 bg-slate-100 p-1 rounded-full">
              <button 
                onClick={() => setLanguage('EN')}
                className={`px-3 py-1 rounded-full text-xs font-bold transition-all ${language === 'EN' ? 'bg-white text-brand shadow-sm' : 'text-slate-500'}`}
              >
                EN
              </button>
              <button 
                onClick={() => setLanguage('HI')}
                className={`px-3 py-1 rounded-full text-xs font-bold transition-all ${language === 'HI' ? 'bg-white text-brand shadow-sm' : 'text-slate-500'}`}
              >
                HI
              </button>
            </div>
          </div>
        </div>
      </header>

      <main className="flex-1 max-w-7xl mx-auto w-full p-4 md:p-8">
        {!result && !isAnalyzing && (
          <motion.div 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="max-w-2xl mx-auto space-y-8 py-12"
          >
            <div className="text-center space-y-4">
              <h2 className="text-4xl font-extrabold text-slate-900 tracking-tight">
                {t.heroTitle}<span className="text-brand">{t.heroTitleHighlight}</span>
              </h2>
              <p className="text-lg text-slate-600">
                {t.heroSub}
              </p>
            </div>

            <div className="bg-white p-6 rounded-2xl shadow-xl border border-slate-100 space-y-6">
              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <label className="text-xs font-bold text-slate-500 uppercase tracking-wider flex items-center gap-1">
                    <User className="w-3 h-3" /> {t.patientAge}
                  </label>
                  <input 
                    type="number" 
                    value={age}
                    onChange={(e) => setAge(e.target.value)}
                    className="w-full px-4 py-2 bg-slate-50 border border-slate-200 rounded-lg focus:ring-2 focus:ring-brand focus:border-transparent outline-none transition-all"
                  />
                </div>
                <div className="space-y-2">
                  <label className="text-xs font-bold text-slate-500 uppercase tracking-wider flex items-center gap-1">
                    <Languages className="w-3 h-3" /> {t.language}
                  </label>
                  <select 
                    value={language}
                    onChange={(e) => setLanguage(e.target.value as Language)}
                    className="w-full px-4 py-2 bg-slate-50 border border-slate-200 rounded-lg focus:ring-2 focus:ring-brand focus:border-transparent outline-none transition-all"
                  >
                    <option value="EN">English</option>
                    <option value="HI">Hindi (हिंदी)</option>
                  </select>
                </div>
              </div>

              <div 
                onClick={() => fileInputRef.current?.click()}
                className={`border-2 border-dashed rounded-xl p-12 text-center cursor-pointer transition-all hover:bg-brand-light hover:border-brand ${file ? 'border-brand bg-brand-light' : 'border-slate-200'}`}
              >
                <input 
                  type="file" 
                  ref={fileInputRef}
                  onChange={handleFileChange}
                  accept="image/*,application/pdf"
                  className="hidden"
                />
                <div className="flex flex-col items-center gap-3">
                  <div className={`p-4 rounded-full ${file ? 'bg-brand text-white' : 'bg-slate-100 text-slate-400'}`}>
                    <Upload className="w-8 h-8" />
                  </div>
                  <div>
                    <p className="font-bold text-slate-900">
                      {file ? file.name : t.uploadText}
                    </p>
                    <p className="text-sm text-slate-500">{t.uploadSub}</p>
                  </div>
                </div>
              </div>

              {error && (
                <div className="bg-red-50 text-red-600 p-4 rounded-lg flex items-center gap-3 text-sm">
                  <AlertCircle className="w-5 h-5 flex-shrink-0" />
                  {error}
                </div>
              )}

              <button 
                onClick={analyzeDocument}
                disabled={!file}
                className="w-full bg-brand hover:bg-brand-dark disabled:bg-slate-300 text-white font-bold py-4 rounded-xl shadow-lg shadow-brand/20 flex items-center justify-center gap-2 transition-all active:scale-95"
              >
                {t.analyzeBtn} <ArrowRight className="w-5 h-5" />
              </button>
            </div>
          </motion.div>
        )}

        {isAnalyzing && (
          <div className="max-w-md mx-auto py-24 text-center space-y-8">
            <div className="relative inline-block">
              <Loader2 className="w-16 h-16 text-brand animate-spin" />
              <div className="absolute inset-0 flex items-center justify-center">
                <Activity className="w-6 h-6 text-brand animate-pulse" />
              </div>
            </div>
            <div className="space-y-4">
              <h3 className="text-2xl font-bold text-slate-900">{t.scanning}</h3>
              <div className="space-y-2">
                {t.steps.map((s, i) => (
                  <motion.div 
                    key={s}
                    initial={{ opacity: 0, x: -10 }}
                    animate={{ opacity: i <= step ? 1 : 0.3, x: 0 }}
                    className="flex items-center gap-3 text-sm font-medium text-slate-600"
                  >
                    {i < step ? <CheckCircle2 className="w-4 h-4 text-emerald-500" /> : <div className="w-4 h-4 rounded-full border border-slate-300" />}
                    {s}
                  </motion.div>
                ))}
              </div>
            </div>
          </div>
        )}

        {result && (
          <motion.div 
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            className="space-y-8 pb-24"
          >
            {/* Action Bar */}
            <div className="flex items-center justify-between no-print">
              <button 
                onClick={() => setResult(null)}
                className="text-slate-500 hover:text-slate-900 flex items-center gap-1 text-sm font-medium"
              >
                <History className="w-4 h-4" /> {t.startNew}
              </button>
              <div className="flex items-center gap-3">
                <button 
                  onClick={copyToWhatsApp}
                  className="bg-emerald-500 hover:bg-emerald-600 text-white px-4 py-2 rounded-lg text-sm font-bold flex items-center gap-2 transition-all"
                >
                  <Share2 className="w-4 h-4" /> {t.whatsapp}
                </button>
                <button 
                  onClick={() => window.print()}
                  className="bg-slate-900 hover:bg-black text-white px-4 py-2 rounded-lg text-sm font-bold flex items-center gap-2 transition-all"
                >
                  <Printer className="w-4 h-4" /> {t.print}
                </button>
              </div>
            </div>

            {/* Dashboard Grid */}
            <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
              {/* Main Column */}
              <div className="lg:col-span-2 space-y-8">
                {/* Diagnosis Card */}
                <div className="bg-white p-8 rounded-2xl shadow-sm border border-slate-200 card">
                  <div className="flex items-start justify-between mb-6">
                    <div>
                      <label className="text-xs font-bold text-slate-400 uppercase tracking-widest">{t.diagnosis}</label>
                      <h2 className="text-3xl font-extrabold text-slate-900">{result.diagnosis}</h2>
                    </div>
                    <div className="bg-brand-light p-3 rounded-xl">
                      <Activity className="text-brand w-6 h-6" />
                    </div>
                  </div>
                  <div className="bg-slate-50 p-6 rounded-xl border border-slate-100">
                    <p className="text-slate-700 leading-relaxed italic">
                      "{result.family_summary}"
                    </p>
                  </div>
                </div>

                {/* Medications Table */}
                <div className="bg-white rounded-2xl shadow-sm border border-slate-200 overflow-hidden card">
                  <div className="p-6 border-b border-slate-100 flex items-center gap-2">
                    <Pill className="text-brand w-5 h-5" />
                    <h3 className="font-bold text-slate-900">{t.medSchedule}</h3>
                  </div>
                  <div className="overflow-x-auto">
                    <table className="w-full text-left">
                      <thead>
                        <tr className="bg-slate-50 text-slate-500 text-xs font-bold uppercase tracking-wider">
                          <th className="px-6 py-4">{t.medicine}</th>
                          <th className="px-6 py-4">{t.dosage}</th>
                          <th className="px-6 py-4">{t.frequency}</th>
                          <th className="px-6 py-4">{t.why}</th>
                        </tr>
                      </thead>
                      <tbody className="divide-y divide-slate-100">
                        {result.medications.map((med, i) => (
                          <tr key={i} className="hover:bg-slate-50 transition-colors">
                            <td className="px-6 py-4 font-bold text-slate-900">{med.name}</td>
                            <td className="px-6 py-4 text-slate-600">{med.dosage}</td>
                            <td className="px-6 py-4 text-slate-600">
                              <span className="bg-brand-light text-brand-dark px-2 py-1 rounded text-xs font-bold">
                                {med.frequency}
                              </span>
                            </td>
                            <td className="px-6 py-4 text-slate-500 text-sm">{med.purpose}</td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                </div>

                {/* Jargon Buster */}
                <div className="bg-white p-8 rounded-2xl shadow-sm border border-slate-200 card">
                  <div className="flex items-center gap-2 mb-6">
                    <Info className="text-brand w-5 h-5" />
                    <h3 className="font-bold text-slate-900">{t.jargonBuster}</h3>
                  </div>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    {result.original_vs_simple.map((pair, i) => (
                      <div key={i} className="flex flex-col p-4 bg-slate-50 rounded-xl border border-slate-100">
                        <span className="text-xs font-bold text-slate-400 uppercase mb-1">{pair.jargon}</span>
                        <span className="text-slate-900 font-medium">{pair.simple}</span>
                      </div>
                    ))}
                  </div>
                </div>
              </div>

              {/* Sidebar Column */}
              <div className="space-y-8">
                {/* Follow-up Card */}
                <div className="bg-slate-900 text-white p-8 rounded-2xl shadow-xl card">
                  <h3 className="text-xl font-bold mb-6 flex items-center gap-2">
                    <Clipboard className="w-5 h-5 text-brand" /> {t.nextSteps}
                  </h3>
                  <ul className="space-y-4">
                    {result.followup.map((item, i) => (
                      <li key={i} className="flex items-start gap-3">
                        <div className="mt-1.5 w-1.5 h-1.5 rounded-full bg-brand flex-shrink-0" />
                        <span className="text-slate-300 text-sm leading-relaxed">{item}</span>
                      </li>
                    ))}
                  </ul>
                </div>

                {/* Side Effects Card */}
                <div className="bg-amber-50 border border-amber-100 p-8 rounded-2xl card">
                  <h3 className="text-amber-900 font-bold mb-4 flex items-center gap-2">
                    <AlertCircle className="w-5 h-5" /> {t.watchFor}
                  </h3>
                  <ul className="space-y-3">
                    {result.side_effects.map((effect, i) => (
                      <li key={i} className="text-amber-800 text-sm flex items-center gap-2">
                        <div className="w-1 h-1 rounded-full bg-amber-400" />
                        {effect}
                      </li>
                    ))}
                  </ul>
                  <p className="mt-6 text-[10px] text-amber-600 uppercase font-bold tracking-widest">
                    {t.contactDoctor}
                  </p>
                </div>

                {/* Print Footer (Hidden on screen) */}
                <div className="hidden print-only pt-12 border-t border-slate-200 mt-12">
                  <div className="flex justify-between items-end">
                    <div>
                      <p className="text-xs text-slate-400">{t.generatedBy}</p>
                      <p className="text-[10px] text-slate-400 mt-1 italic">{t.printDisclaimer}</p>
                    </div>
                    <div className="text-right">
                      <p className="text-xs font-bold text-brand">{t.dashboard}</p>
                      <p className="text-[10px] text-slate-400">{new Date().toLocaleDateString()}</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </motion.div>
        )}
      </main>

      {/* Footer */}
      <footer className="bg-white border-t border-slate-100 py-8 no-print">
        <div className="max-w-7xl mx-auto px-4 text-center space-y-2">
          <p className="text-sm text-slate-500 font-medium">
            MedBuddy — IAR Udaan Hackathon 2026
          </p>
          <p className="text-[10px] text-slate-400 max-w-md mx-auto">
            {t.footerDisclaimer}
          </p>
        </div>
      </footer>
    </div>
  );
}
